import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Подключаем Inter
const inter = Inter({
  variable: "--font-inter-sans",
  subsets: ["cyrillic"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <head>
        <meta charSet="UTF-8"></meta>
      </head>
      <body
        className={`$InterSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
